- name: Install Nginx
  yum:
    name: "nginx"
    state: "present"

- name: Put nginx conf file
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx.root }}/nginx.conf"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"
  register: result_put_nginx_conf

- name: Put logrotate conf
  template:
    src: "nginx.rotate.conf.j2"
    dest: "/etc/logrotate.d/nginx"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0644"
  register: result_put_logrotate_conf

- name: make directory
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"
  with_items:
    - "{{ nginx.logdir }}"
    - "{{ nginx.root }}"

- name: Restart Nginx
  systemd:
    name: nginx.service
    state: restarted
    enabled: True
  when: >
    (result_put_nginx_conf is changed ) or
    (result_put_logrotate_conf is changed )
