- name: Install Nginx
  yum:
    name: "nginx"
    state: "present"

- name: Put nginx conf file
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx.root }}/nginx.conf"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"

- name: Put logrotate conf
  template:
    src: "nginx.rotate.conf.j2"
    dest: "/etc/logrotate.d/nginx"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0644"

- name: set chmod
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"
  with_items:
    - "{{ nginx.logdir }}"
    - "{{ nginx.root }}"

- name: Restart Nginx
  systemd:
    name: nginx.service
    state: restarted
    enabled: True
