# - name: Put Nginx repo
#   become: yes
#   copy:
#     src: nginx.repo
#     dest: "/etc/yum.repos.d/nginx.repo"
#     owner: root
#     group: root
#     mode: "0644"

- name: Install Nginx
  yum:
    name: "nginx"
    state: "present"
    # enablerepo: "nginx"

- name: Put nginx conf file
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx.root }}/nginx.conf"
    owner: "{{ nginx.user }}"
    group: "{{ nginx.group }}"
    mode: "0755"

- name: Put logrotate conf
  template:
    src: "nginx.rotate.conf.j2"
    dest: "/etc/logrotate.d/nginx"
    owner: "{{ nginx.user }}"
    group: "{{ nginx.group }}"
    mode: "0644"

- name: set chmod
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ nginx.user }}"
    group: "{{ nginx.group }}"
    mode: "0755"
  with_items:
    - "{{ nginx.logdir }}"
    - "{{ nginx.root }}"

- name: Restart Nginx
  systemd:
    name: nginx.service
    state: restarted
    enabled: True
